name: build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux-and-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build (Linux)
        run: nix develop -c cargo build --release

      - name: Build (Windows cross)
        run: nix develop .#windows -c cargo build --release

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: bwtools-linux
          path: target/release/bwtools

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: bwtools-windows
          path: target/x86_64-pc-windows-gnu/release/bwtools.exe

      - name: Create GitHub Release (tagged builds)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/bwtools
            target/x86_64-pc-windows-gnu/release/bwtools.exe
