name: build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build (Linux)
        run: nix develop -c cargo build --release

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: bwtools-linux
          path: target/release/bwtools

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (Windows MSVC)
        run: cargo build --release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: bwtools-windows
          path: target/release/bwtools.exe

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: bwtools-linux
          path: dist

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: bwtools-windows
          path: dist

      - name: Create GitHub Release (tagged builds)
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bwtools
            dist/bwtools.exe
